FROM openjdk:8
MAINTAINER Shubham Aggarwal shubhamaggarwal890@gmail.com
COPY ./target/myCalc-1.0-SNAPSHOT-jar-with-dependencies.jar ./
WORKDIR ./
CMD ["java", "-jar", "mycalc-1.0-SNAPSHOT-jar-with-dependencies.jar"]
